### PR TITLE
OP-18 Max and min for all day temp for Weekly weather report.

### PR DESCRIPTION
**Pull request by StriMer22**

### CODE REVIEW

**Review by AlexUlianets — COMMENTED** [review]
Why did you delete  
-    private int temperatureC;
-    private int temperatureF;
you should have added max and min for left side block only, not to change sth.

**Comment by StriMer22** [comment]
Those params were max temperature for day, instantly was wrongly named, all we needed to do is to add
min temp for day, to avoid any regressions and misunderstands we had to rename the existing param.

**Comment by AlexUlianets** [comment]
I see, but how about those params? I use 
private int temperatureC;
private int temperatureF;

**Comment by StriMer22** [comment]
they stays the same. the temperature param from the column is the biggest value for day parts(day, night)

Always the biggest temperature is in day, so that param duplicates in the table,
what about min temperature, it was got as an existing param.

**Review by AlexUlianets — APPROVED** [review]

**Pull request merged**
